name: dyvision
description: A smart vocabulary trainer for dyslexics.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.1
  #flutter_mobile_vision: ^0.1.3
  flutter_svg: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: fonts/OpenDyslexic/OpenDyslexic-Regular.otf
        - asset: fonts/OpenDyslexic/OpenDyslexic-Italic.otf
          style: italic
        - asset: fonts/OpenDyslexic/OpenDyslexic-Bold.otf
          weight: 400
        - asset: fonts/OpenDyslexic/OpenDyslexic-BoldItalic.otf
          weight: 400
          style: italic
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 100
        - asset: fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 200
        - asset: fonts/Nunito/Nunito-LightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 500
        - asset: fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 600
          style: italic

